server:
  port: 8080


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        '[/**]':
          cors-configuration:
            allowed-origins: "*"
            allowed-headers:
              - content-type
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/*
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/*
          filters:
            - RewritePath=/posts/(?<path>.*), /*\{path}