server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers:
              - content-type
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), $\{segment}
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts(?<segment>/?.*), $\{segment}