server:
  port: 8761 # This is the default port a Eureka server is expected

spring:
  application:
    name: discovery-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
